---
title: "Daphnia Populations"
author: "Jo"
date: "07/02/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("data_set_up.R")
library(multcomp)
library(lmerTest)
```

daphnia populations
```{r daphnia populations}
pop1 <- pop %>% filter(! treatment %in% c(5,6,9,10,13,14))
pop1$disturb <- "X"
  
for (i in 1:nrow(pop1)){
  if (pop1$treatment[i] ==2| pop1$treatment[i] ==4| pop1$treatment[i] ==8|
      pop1$treatment[i] ==12){
    pop1$disturb[i] <- "y"
  } else if (pop1$treatment[i] ==1|pop1$treatment[i] ==3|pop1$treatment[i] ==7|pop1$treatment[i] ==11){
    pop1$disturb[i] <- "n"
  }}

pop1$animal <- "X"

for (i in 1:nrow(pop1)){
  if (pop1$treatment[i] ==3| pop1$treatment[i] ==4){
    pop1$animal[i] <- "daphnia"
  } else if (pop1$treatment[i] ==7|pop1$treatment[i] ==8){
    pop1$animal[i] <- "snail"
  } else if (pop1$treatment[i] ==11|pop1$treatment[i] ==12){
    pop1$animal[i] <- "both"}
  else if (pop1$treatment[i] ==1|pop1$treatment[i] ==2){
    pop1$animal[i] <- "none"}
}

popA <- pop1 %>% dplyr::select(TankNum, treatment,animal, disturb, Exptday, daphniaC1Adult,daphniaC2Adult,daphniaC3,
                       daphniaC4Adult,Liters, daphniaC1Juv,daphniaC2Juv,daphniaC3Juv,
                       daphniaC4Juv)
popA <- popA %>% gather(key = "subsample", value= "count", -c(TankNum,treatment, Exptday, Liters, animal, disturb))

popB <- popA %>% separate(subsample, into=c("daphnia","subsample","stage"),sep ='([[:upper:]])', extra = "drop", fill = "right" )


popB <- popB %>% group_by(TankNum, Exptday, subsample, animal, disturb) %>% 
  summarize(total = sum(count))
popB <- left_join(popB, block, by= "TankNum")

```

Final Population
```{r daphnia final pop}
pop_fin <- popB %>% group_by(TankNum) %>% filter(Exptday == max(Exptday))


pop_fin$treat <- paste(pop_fin$animal,pop_fin$disturb)

pop_fin$animal <- factor(pop_fin$animal, levels = c("daphnia","both"))
pop_fin$disturb <- factor(pop_fin$disturb, levels = c("y","n"))

daph_fin_mod <- glmer(total ~ -1 + animal*disturb + (1|TankNum) + (1|block),data = pop_fin, family = "poisson" ) 
plot(resid(daph_fin_mod))
qqnorm(resid(daph_fin_mod))

## check for overdispersion based on https://bbolker.github.io/mixedmodels-misc/glmmFAQ.html
overdisp_fun <- function(model) {
    rdf <- df.residual(model)
    rp <- residuals(model,type="pearson")
    Pearson.chisq <- sum(rp^2)
    prat <- Pearson.chisq/rdf
    pval <- pchisq(Pearson.chisq, df=rdf, lower.tail=FALSE)
    c(chisq=Pearson.chisq,ratio=prat,rdf=rdf,p=pval)
}


overdisp_fun(daph_fin_mod) ## this is overdispersed

## so use negative binomial 
daph_fin_nb <- glmer.nb(total ~ -1 + animal*disturb + (1|TankNum) + (1|block),data = pop_fin)
## desired contrast is the interaction term

```


graphnig
```{r}
##for graphing
pfin1 <- emmeans(daph_fin_nb, ~animal*disturb)
pfin2 <- data.frame(confint(pairs(pfin1, simple = "disturb")))

```


graph
```{r plot final pop}
popg <- ggplot(data = pfin2, aes(exp(estimate), animal)) + geom_point(size=4) + geom_errorbarh(aes(xmin=exp(asymp.LCL), xmax = exp(asymp.UCL)), height = 0.3) + ylab("") + xlab(str_wrap("Proportional Change in Final Population", width = 25)) + theme(axis.line = element_line(colour = "black"), panel.border = element_blank()) + geom_vline(xintercept = 1, color = "gray68", linetype = "dashed") + scale_y_discrete(labels = str_wrap(c("Daphnia","Daphnia and Physa" ), width = 10))

```

save to pdf
```{r}
pdf(file = "daph_pop_change.pdf", width =5, height = 4)
popg
dev.off()

```

```{r plot final pop}
e1_pop <-  emmeans(daph_fin_nb, ~animal*disturb, type = "response")

popgd <- data.frame(e1_pop)
popgd$treat <- paste(popgd$animal,popgd$disturb)

popg_full <- ggplot(data = popgd, aes(treat,response)) +  
   geom_point(size = 4) + geom_errorbar(aes(ymin= asymp.LCL, ymax=asymp.UCL), width = 0.3)+ ylab("Daphnia magna per 10mL") + 
  xlab(" ")+ theme(axis.line = element_line(colour = "black"), panel.border = element_blank())  + ggtitle("A. Final Population")+ theme(legend.position = "none") + 
  scale_x_discrete(labels = str_wrap(c("Daphnia and Physa Not Disturbed", "Daphnia and Physa Disturbed", "Daphia Not Disturbed", "Daphnia Disturbed"),width = 8))


```


Max population- post disturbance
```{r daphnia max}

pop_post <- popB %>% filter(Exptday > 19) 


pop_max <- pop_post %>% group_by(TankNum, Exptday) %>% mutate(mean_pop = mean(total),
                                                              sd_pop = sd(total))
   

pop_max1 <- pop_max %>% group_by(TankNum) %>% filter(mean_pop == max(mean_pop))
pop_max2 <- pop_max1 %>% group_by(TankNum) %>% slice(1)


dim(pop_max2)

pop_max2$animal <- factor(pop_max2$animal, levels = c("daphnia","both"))
## weights multiplication of squared residuals

daph_max_mod_p <- lmer(log(mean_pop)~-1+animal*disturb + (1|block), data = pop_max2, weights = 1/sd_pop^2)


## refit with parameters for each group
dd2 <- update(daph_max_mod_p, ~ -1 + animal:disturb + (1|block))
cc1 <- confint(dd2,parm="beta_",method="Wald")
res <- data.frame(ttt=names(fixef(dd2)),
                  est=fixef(dd2),
                  setNames(as.data.frame(cc1),c("lwr","upr")),
                  stringsAsFactors=FALSE)
rownames(res) <- NULL

## cc2 <- confint(dd2,parm="beta_")  ## ugh

## ((b1-b3)- (b2-b4)) = b1 - b3 - b2 + b4 = b1 - b2 - b3 + b4

### testing hypothesis
confint(glht(dd2, linfct=matrix(c(1,-1,-1,1),nrow=1)))
## sub-contrasts
cc3 <- confint(glht(dd2, linfct=matrix(c(-1,0,1,0,
                                         0,-1,0,1),
                                       nrow=2,byrow=TRUE)))
dd3 <- data.frame(term=c("Both","Daphnia"),
           cc3$confint)
ggplot(dd3,aes(term,Estimate,ymin=lwr,ymax=upr))+
  geom_pointrange() + coord_flip()

### end BMB junk

```


graph
```{r plot final pop}
## reorder levels to match other datasets
dd3$term <- factor(dd3$term, levels= c("Daphnia", "Both"))

popmax1 <- ggplot(data = dd3, aes(exp(Estimate), term)) + geom_point(size=4) + geom_errorbarh(aes(xmin=exp(lwr), xmax = exp(upr)), height = 0.3) + ylab(" ") + xlab(str_wrap("Proportional Change in Maximum Population", width = 25)) + theme(axis.line = element_line(colour = "black"), panel.border = element_blank()) + geom_vline(xintercept = 1, color = "gray68", linetype = "dashed") + scale_y_discrete(labels = str_wrap(c("Daphnia","Daphnia and Physa" ), width = 10))
```

save to pdf
```{r}
pdf(file = "max_pop_change.pdf", width = 5, height = 4)
popmax1
dev.off()
```


```{r plot pop max}

res$animal <- c("both", "daphnia", "both", "daphnia")
res$disturb <- c("n", "n", "y","y")
res$ttt<- paste(res$animal,res$disturb)

popg_max <- ggplot(data = res, aes(ttt,exp(est))) +  
   geom_point(size = 4) + geom_errorbar(aes(ymin= exp(lwr), ymax=exp(upr)), width = 0.3)+ ylab("Daphnia magna per 10 mL ") + 
  xlab(" ")+ theme(axis.line = element_line(colour = "black"), panel.border = element_blank()) +
  ggtitle("B. Maximum population")  + theme(legend.position = "none") + 
  scale_x_discrete(labels =str_wrap(c("Daphnia and Physa Not Disturbed", "Daphnia and Physa Disturbed", "Daphia Not Disturbed", "Daphnia Disturbed"),width = 8))

print(popg_max)

grid.arrange(popg_full, popg_max)

```

save to pdf
```{r}
pdf(file = "daphnia_pop.pdf", width = 7, height = 11)
grid.arrange(popg_full, popg_max)
dev.off()


```



Ephippia presence
```{r daphnia egg cases}
egg <- read.csv("egg_case.csv")
names(egg) <- c("TankNum","eggs")
dim(egg)
newdat1 <- dat %>%filter(ExptDay == 1)%>% dplyr::select(TankNum, animal, disturb, block)
egg1 <- left_join( egg, newdat1)
dim(egg1)
newdat2 <- newdat %>% filter(ExptDay ==1) %>% dplyr::select(TankNum,treatment)
egg1 <- left_join(egg1,newdat2)
dim(egg1)
egg2 <- egg1 %>% filter(! treatment %in% c(5,6,9,10,13,14))
dim(egg2)
egg4 <- egg2 %>% filter(animal %in% c("both","daphnia"))
```

```{r egg case model}
egg4$animal <- factor(egg4$animal, levels= c("daphnia", "both"))
egg4$eggs <- as.factor(egg4$eggs)
str(egg4)
eggmod <- glmer(eggs~-1+animal*disturb + (1|block), family = binomial(link= logit), data = egg4)
## estimate main effects at midpoint by using sum-to-zero contrasts-- why did I do this?? 
## (probably better)
eggmod_cs <- update(eggmod, contrasts=list(animal=contr.sum,disturb=contr.sum))


```


```{r plot_eggcases}
## 1. this is probably the best representation
plot(emmeans(eggmod,~animal*disturb)) #,type="response")
## if you want to plot this yourself:
dd <- as.data.frame(emmeans(eggmod,~animal*disturb),type="response")

dd$treat <- paste(dd$animal,dd$disturb)

eggg <- ggplot(data = dd, aes(treat, prob)) + geom_point( size = 4) + geom_errorbar(aes(ymin= asymp.LCL, ymax=asymp.UCL), width = 0.3)+ ylab("Probablity Ephippium Present") + 
  xlab(" ")+ theme(axis.line = element_line(colour = "black"), panel.border = element_blank()) +
  scale_x_discrete(labels =str_wrap(c("Daphnia and Physa Not Disturbed", "Daphnia and Physa Disturbed", "Daphia Not Disturbed", "Daphnia Disturbed"),width = 8))


print(eggg)
```

save to pdf
```{r}
pdf(file = "ephippium.pdf", width = 4, height = 5)
eggg
dev.off()

```


