---
title: "Disturbance_contrasts"
author: "Jo"
date: "31/01/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("data_set_up.R")
dat$animal <- factor(dat$animal, levels = c("none", "snail", "daphnia", "both"))
dat$disturb <- factor(dat$disturb, levels = c("y","n"))
```




Subset final time point for Nh4 and final 4 days for Chl
```{r final time point}
fday <- dat %>% filter(ExptDay == 40)
l <- as.numeric(unique(fday$TankNum))
fday1 <- dat %>% filter(ExptDay == 39) %>% filter(TankNum !=20 & TankNum !=21 & TankNum !=22 & TankNum != 23 &
                                                  TankNum !=24 & TankNum !=25 & TankNum !=26 & TankNum != 27 & 
                                                  TankNum !=28 & TankNum !=29 & TankNum !=30 & TankNum != 31 & 
                                                  TankNum !=32 & TankNum !=33 & TankNum !=34 & TankNum != 35 & 
                                                  TankNum !=36 & TankNum !=37 & TankNum !=38 & TankNum != 39 & 
                                                  TankNum !=40 & TankNum !=83 & TankNum !=84 & TankNum != 85 & 
                                                  TankNum !=86 & TankNum !=87 & TankNum !=88 & TankNum != 89 & 
                                                  TankNum !=90 & TankNum !=91 & TankNum !=92 & TankNum != 93 &
                                                  TankNum !=94 & TankNum !=95 & TankNum !=96 & TankNum != 97 & 
                                                  TankNum !=98 & TankNum !=99 & TankNum !=100& TankNum != 101 & 
                                                  TankNum != 102 & TankNum != 103 & TankNum != 104 & TankNum != 105 & 
                                                  TankNum != 106 & TankNum != 107) 
finday <- rbind(fday, fday1)
dim(finday)


endday <- dat %>% filter(ExptDay == 40 | ExptDay == 39 | ExptDay == 38 | ExptDay == 37)
endday1 <- dat %>% filter(ExptDay == 36) %>% filter(TankNum !=20 & TankNum !=21 & TankNum !=22 & TankNum != 23 &
                                                  TankNum !=24 & TankNum !=25 & TankNum !=26 & TankNum != 27 & 
                                                  TankNum !=28 & TankNum !=29 & TankNum !=30 & TankNum != 31 & 
                                                  TankNum !=32 & TankNum !=33 & TankNum !=34 & TankNum != 35 & 
                                                  TankNum !=36 & TankNum !=37 & TankNum !=38 & TankNum != 39 & 
                                                  TankNum !=40 & TankNum !=83 & TankNum !=84 & TankNum != 85 & 
                                                  TankNum !=86 & TankNum !=87 & TankNum !=88 & TankNum != 89 & 
                                                  TankNum !=90 & TankNum !=91 & TankNum !=92 & TankNum != 93 &
                                                  TankNum !=94 & TankNum !=95 & TankNum !=96 & TankNum != 97 & 
                                                  TankNum !=98 & TankNum !=99 & TankNum !=100& TankNum != 101 & 
                                                  TankNum != 102 & TankNum != 103 & TankNum != 104 & TankNum != 105 & 
                                                  TankNum != 106 & TankNum != 107)

end <- rbind(endday, endday1)

```

Final day model
```{r}
##remove 2 NA values
finmod00 <- lmer(log10(adj_chl) ~ -1 + animal*disturb + (1|block), data =  end[end$adj_chl > 0, ])
plot(resid(finmod00))
qqnorm(resid(finmod00))

```

Contrasts of interest
```{r}
## difference of differences (6 contrasts)
chlfin <- contrast(regrid(emmeans(finmod00, ~animal*disturb)), interaction = c("pairwise"), by = NULL)

## difference between disturbed treatments across herbivores (5 contrasts)


##for graphing
chlfin1 <- emmeans(finmod00, ~animal*disturb)
chlfin2 <- data.frame(confint(pairs(chlfin1, simple = "disturb")))

```

Find maximum three day window 
```{r chl max}
dat <- dat %>% filter(!is.na(adj_chl))
#dat_dist <- dat %>% filter(ExptDay >= ExptDay[which(dat$Disturbed=="y")]) ## only days after disturbance, this doesn't work for non-disturbed treatments- obviously
dat_dist <- dat %>% filter(ExptDay > 19)

chl_rollmean <- dat_dist %>% group_by(treatment) %>%
    tq_mutate(
        # tq_mutate args
        select     = adj_chl,
        mutate_fun = rollapply, 
        
        # rollapply args
        width      = 3,
        FUN        = mean,
        # mean args
        na.rm  = TRUE,
        # tq_mutate args
        col_rename = "mean_3"
    )   %>%
 ungroup()


max_chl <- chl_rollmean %>% group_by(TankNum) %>% 
  dplyr::select(TankNum,treatment,animal, disturb,mean_3, block) %>%
  filter(mean_3 == max(mean_3, na.rm = T))

max_chl$animal <- as.factor(max_chl$animal)
## Put the order of the factors in a more reasonable order
max_chl$animal <- factor(max_chl$animal, levels = c("none", "snail", "daphnia", "both"))
max_chl$disturb <- as.factor(max_chl$disturb)
max_chl$disturb <- factor(max_chl$disturb, levels = c("y","n"))
``` 

linear model
```{r}
maxmod <- lmer(log10(mean_3) ~ -1+animal*disturb + (1|block), data = max_chl)
plot(resid(maxmod))
qqnorm(resid(maxmod))
```

contrasts of interest
```{r}


###compares differences of differences- checked with output of summany(maxmod)- gets correct mean estimates
 
mchl <- contrast(regrid(emmeans(maxmod, ~animal*disturb)), interaction = c("pairwise"), by = NULL)

summary(maxmod)

##for graphing
mchl1 <- emmeans(maxmod, ~animal*disturb)
mchl2 <- data.frame(confint(pairs(mchl1, simple = "disturb")))


```


Ammonium final day
```{r}

amm_final <- lmer(log10(NH4)~animal*disturb + (1|block), data = finday)
plot(resid(amm_final))
qqnorm(resid(amm_final))
```

Contrasts
```{r}
ammfin <- contrast(regrid(emmeans(amm_final, ~animal*disturb)), interaction = c("pairwise"), by = NULL)

##for graphing
ammfin1 <- emmeans(amm_final, ~animal*disturb)
ammfin2 <- data.frame(confint(pairs(ammfin1, simple = "disturb")))
```

Ammonium maximum model
```{r}
## make column with max NH4 reached after day 19
dat_max <- dat %>% filter(ExptDay > 19) %>% group_by(TankNum) %>% mutate(max_nh4= max(NH4,na.rm = T)) %>% ungroup()
#filter for only days with highest ammonium reached
dat_max2 <- dat_max %>% group_by(TankNum) %>% filter(NH4==max_nh4)

amm_max <- lmer(log10(NH4) ~ animal*disturb + (1|block), data = dat_max2)
plot(resid(amm_max))
qqnorm(resid(amm_max))

```
Contrasts
```{r}
mfin <- contrast(regrid(emmeans(amm_max, ~animal*disturb)),interaction = c("pairwise"), by = NULL)

##for graphing
mfin1 <- emmeans(amm_max, ~animal*disturb)
mfin2 <- data.frame(confint(pairs(mfin1, simple = "disturb")))

```
Graphing
```{r}
g <- ggplot(data = chlfin2, aes((estimate), animal)) + geom_point(size=4) + geom_errorbarh(aes(xmin=(lower.CL), xmax = (upper.CL)), height = 0.3) + ylab("") + xlab(str_wrap("Log10 Fold Change Final Chlorophyll (ug/L)", width = 25 )) + theme(axis.line = element_line(colour = "black"), panel.border = element_blank()) + scale_y_discrete(labels = str_wrap(c("No Herbivore",'Physa Only','Daphnia Only', 'Daphnia and Physa'), width= 10)) + geom_vline(xintercept = 0, linetype= "dashed", color = "gray68") + ggtitle("A.")

g1 <- ggplot(data = mchl2, aes(exp(estimate), animal)) + geom_point(size=4) + geom_errorbarh(aes(xmin=exp(lower.CL), xmax = exp(upper.CL)), height = 0.3) + ylab("") + xlab(str_wrap("Log10 Fold Change Maximum Chlorophyll (ug/L)", width = 27)) + theme(axis.line = element_line(colour = "black"), panel.border = element_blank() ) + scale_y_discrete(labels = str_wrap(c("No Herbivore",'Physa Only','Daphnia Only', 'Daphnia and Physa'), width= 10))+ geom_vline(xintercept = 0, linetype= "dashed", color = "gray68") + ggtitle("B.")

g2 <- ggplot(data = ammfin2, aes(exp(estimate), animal)) + geom_point(size=4) + geom_errorbarh(aes(xmin=exp(lower.CL), xmax = exp(upper.CL)), height = 0.3) + ylab("") + xlab(str_wrap("Log10 Fold Change in Final Ammonium (mg/L)",width = 25)) + 
  theme(axis.line = element_line(colour = "black"), panel.border = element_blank()) + scale_y_discrete(labels = str_wrap(c("No Herbivore",'Physa Only','Daphnia Only', 'Daphnia and Physa'), width= 10))+ geom_vline(xintercept = 0, linetype= "dashed", color = "gray68") + ggtitle("A.")

g3 <- ggplot(data = mfin2, aes(exp(estimate), animal)) + geom_point(size=4) + geom_errorbarh(aes(xmin=exp(lower.CL), xmax = exp(upper.CL)), height = 0.3) + ylab(" ") + xlab(str_wrap("Log10 Fold Change in Maximum Ammonium (mg/L)", width = 25)) + 
  theme(axis.line = element_line(colour = "black"), panel.border = element_blank())+ scale_y_discrete(labels = str_wrap(c("No Herbivore",'Physa Only','Daphnia Only', 'Daphnia and Physa'), width= 10)) + geom_vline(xintercept = 0, linetype= "dashed", color = "gray68") + ggtitle("B.")


gl2 <- list(g,g1,g2,g3)
grid.arrange(
  grobs = gl2,
  widths = c(1.3,1),
  layout_matrix = rbind(c(1,2),
                        c(3,4))
)


grid.arrange(g,g1,g2,g3)

```

save to pdf - fyi wont run if figures show in rmarkdown and not on regular plot window

```{r}
pdf(file = 'final_chlorophyl.pdf', width = 5, height = 4)
g
dev.off()

pdf(file = 'max_chlorophyll.pdf', width = 5, height = 4)
g1
dev.off()


pdf(file = 'final_ammonium.pdf', width = 5, height = 4)
g2
dev.off()

pdf(file = 'max_ammonium.pdf', width = 5, height = 4)
g3
dev.off()

```



graph raw data
```{r}
final <- end %>% filter(adj_chl > 0) %>% group_by(animal, disturb) %>% summarize(chl = mean(adj_chl), upper = quantile(adj_chl, 0.975), lower = quantile(adj_chl, 0.025))
final$treat <- paste(final$animal, final$disturb)

final_chl_g <- ggplot(data =final, aes(treat, chl) ) +
  geom_point(size = 3) + geom_errorbar(aes(ymin= lower, ymax = upper), width = 0.3) + xlab(" ") + ylab("\n Final \n Chlorophyll (ug/L)") + theme(legend.position = "none") + theme(axis.line = element_line(colour = "black"), panel.border = element_blank()) + scale_x_discrete(labels = function(x) str_wrap(c("Daphnia and Physa Not Disturbed", "Daphnia and Physa Disturbed", "Daphia Not Disturbed", "Daphnia Disturbed","No Herbivore Not Disturbed", "No Herbivore Disturbed", "Physa Not Disturbed", "Physa Disturbed" ), width = 8)) + ggtitle("C.")


maxchl <- max_chl %>% group_by(animal,disturb) %>% summarize(chl = mean(mean_3), upper = quantile(mean_3,0.975), lower = quantile(mean_3,0.025))
maxchl$treat <- paste(maxchl$animal, maxchl$disturb)

max_chl_g <- ggplot(data= maxchl, aes(treat, chl)) + 
geom_point(size = 3) + geom_errorbar(aes(ymin= lower, ymax = upper), width = 0.3) + xlab(" ") + ylab("\n Maximum \n Chlorophyll (ug/L)") + theme(legend.position = "none") + theme(axis.line = element_line(colour = "black"), panel.border = element_blank()) + scale_x_discrete(labels = function(x) str_wrap(c("Daphnia and Physa Not Disturbed", "Daphnia and Physa Disturbed", "Daphia Not Disturbed", "Daphnia Disturbed","No Herbivore Not Disturbed", "No Herbivore Disturbed", "Physa Not Disturbed", "Physa Disturbed" ), width = 8)) + ggtitle("D.")


nhfin <- finday %>% filter(!is.na(NH4)) %>% group_by(animal, disturb) %>% summarize(amm = mean(NH4), upper = quantile(NH4,0.975), lower = quantile(NH4,0.025))
nhfin$treat <- paste(nhfin$animal,nhfin$disturb)


fin_amm <- ggplot(data = nhfin, aes(treat, amm))  + 
geom_point( size = 3) + geom_errorbar(aes(ymin= lower, ymax = upper), width = 0.3) + xlab(" ") + ylab("\n Final \n Ammonium (mg/L)") + theme(legend.position = "none") + theme(axis.line = element_line(colour = "black"), panel.border = element_blank()) + scale_x_discrete(labels = function(x) str_wrap(c("Daphnia and Physa Not Disturbed", "Daphnia and Physa Disturbed", "Daphia Not Disturbed", "Daphnia Disturbed","No Herbivore Not Disturbed", "No Herbivore Disturbed", "Physa Not Disturbed", "Physa Disturbed"), width = 8)) + ggtitle("C.")

maxamm <- dat_max2 %>% group_by(disturb, animal) %>% summarize(amm = mean(NH4), upper = quantile(NH4,0.975), lower = quantile(NH4,0.025))
maxamm$treat <- paste(maxamm$animal,maxamm$disturb)

max_amm <- ggplot(data = maxamm, aes(treat, amm))  + 
geom_point(size = 3) + geom_errorbar(aes(ymin= lower, ymax = upper), width = 0.3) + xlab(" ") + ylab("\n Maximum \n Ammonium (mg/L)") + theme(legend.position = "none") + theme(axis.line = element_line(colour = "black"), panel.border = element_blank())  + scale_x_discrete(labels = function(x) str_wrap(c("Daphnia and Physa Not Disturbed", "Daphnia and Physa Disturbed", "Daphia Not Disturbed", "Daphnia Disturbed","No Herbivore Not Disturbed", "No Herbivore Disturbed", "Physa Not Disturbed", "Physa Disturbed" ), width = 8)) + ggtitle("D.")



pdf(file = "max_ammonium_raw.pdf", width = 7 , height = 5)
max_amm
dev.off()

pdf(file = "final_ammonium_raw.pdf", width = 7 , height = 5)
fin_amm
dev.off()

pdf(file = "max_chl_raw.pdf", width = 7 , height = 5)
max_chl_g
dev.off()

pdf(file = "final_chl_raw.pdf", width = 7 , height = 5)
final_chl_g
dev.off()

```



```{R}

chl2 <- list(g, g1,  final_chl_g, max_chl_g)

grid.arrange(
  grobs = chl2,
  widths = c(1,1),
  layout_matrix = rbind(c(1,2),
                        c(3,3),
                          c(4,4))
)


nh2 <- list(g2, g3, fin_amm, max_amm)

grid.arrange(
  grobs = nh2,
  widths = c(1,1),
  layout_matrix = rbind(c(1,2),
                        c(3,3),
                          c(4,4))
)


```