---
title: "Sediment"
author: "Jo"
sed2e: "07/02/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("data_set_up.R")

```

```{r sed2a}
sed <- read.csv("sediment.csv")
newdat <- newdat %>%filter(ExptDay == 1)%>% dplyr::select(TankNum, treatment)
sed1 <- left_join(newdat, sed)
sed1 <- left_join(sed1,block, by= "TankNum")
sed2 <- sed1 %>% filter(! treatment %in% c(5,6,9,10,13,14))

sed2$disturb <- "X"
  
for (i in 1:nrow(sed2)){
  if (sed2$treatment[i] ==2| sed2$treatment[i] ==4| sed2$treatment[i] ==8|
      sed2$treatment[i] ==12){
    sed2$disturb[i] <- "y"
  } else if (sed2$treatment[i] ==1|sed2$treatment[i] ==3|sed2$treatment[i] ==7|sed2$treatment[i] ==11){
    sed2$disturb[i] <- "n"
  }}

sed2$animal <- "X"

for (i in 1:nrow(sed2)){
  if (sed2$treatment[i] ==3| sed2$treatment[i] ==4){
    sed2$animal[i] <- "daphnia"
  } else if (sed2$treatment[i] ==7|sed2$treatment[i] ==8){
    sed2$animal[i] <- "snail"
  } else if (sed2$treatment[i] ==11|sed2$treatment[i] ==12){
    sed2$animal[i] <- "both"}
  else if (sed2$treatment[i] ==1|sed2$treatment[i] ==2){
    sed2$animal[i] <- "none"}
}


sed2$animal <- factor(sed2$animal,levels = c("none", "snail", "daphnia", "both"))
sed2$disturb <- factor(sed2$disturb, levels = c("y", "n"))
sed2$block <- as.factor(sed2$block)
dim(sed2)

## average within tank
sed3 <- sed2 %>% group_by(TankNum, animal, disturb,block) %>% summarize(sediment = mean(sediment)) 
dim(sed3)
```


```{r model}
sedmod <- lmer(log10(sediment) ~ -1+ animal*disturb + (1|block),data = sed3 ) ## hmm do all my models need random effect of tank??-- i only have 2 measurement per tank...so that doesn't seem doable but should i do something? 
plot(resid(sedmod))
qqnorm(resid(sedmod)) 

```


```{r contrasts}
sedm <- contrast((emmeans(sedmod, ~animal*disturb)),interaction = c("pairwise"), by = NULL)

##for graphing
sedm1 <- emmeans(sedmod, ~animal*disturb)
sedm2 <- data.frame(confint(pairs(sedm1, simple = "disturb")))

```



plot differences
```{r, echo=FALSE}
(sedg <- ggplot(data = sedm2, aes((estimate), animal)) + geom_point(size=4) + geom_errorbarh(aes(xmin=(lower.CL), xmax = (upper.CL)), height = 0.3) + ylab(" ") + xlab(str_wrap("Log10 Fold Change in Sediment", width = 25)) + theme(axis.line = element_line(colour = "black"), panel.border = element_blank()) + scale_y_discrete(labels = str_wrap(c("No Herbivore",'Physa Only','Daphnia Only', 'Daphnia and Physa'), width= 10)) + geom_vline(xintercept = 0, linetype = "dashed",color = "gray68"))
```

save to pdf
```{r}
pdf(file = "sediment.pdf", width = 5, height =4)
sedg
dev.off()

```

plot 
```{r}

sedest <- as.data.frame(emmeans(sedmod, ~animal*disturb, type ="response"))
sedest$treat <- paste(sedest$animal, sedest$disturb)
sedr_g <- ggplot(data = sedest, aes(treat,response)) + geom_point(size=3) +
  geom_errorbar(aes(ymin=lower.CL, ymax=upper.CL), width = 0.3) + ylab("Sediment (mL)") + 
  xlab(" ")+ theme(axis.line = element_line(colour = "black"), panel.border = element_blank())  + 
   theme(legend.position= "none")+ scale_x_discrete(labels = function(x) str_wrap(c("Daphnia and Physa Not Disturbed", "Daphnia and Physa Disturbed", "Daphia Not Disturbed", "Daphnia Disturbed","No Herbivore Not Disturbed", "No Herbivore Disturbed", "Physa Not Disturbed", "Physa Disturbed" ), width = 8))



```

save to pdf
```{r}
pdf(file = "sediment_raw.pdf", width = 7, height =5)
sedr_g
dev.off()
```

